### ISSUE TITLE
Ordenamento por ordem de citação no sistema numérico

### ISSUE THREAD

**Issue by leonartex** [abntex/abntex2-biblatex#103]
A NBR 6023:2018 estabelece que, utilizando o sistema numérico, "as referências devem ser numeradas de acordo com a ordem sequencial em que aparecem no texto pela primeira vez e colocadas em lista nesta mesma ordem". Eu testei aqui o abnt-numeric e ele não realiza isso e também dei uma olhada no código e apenas tem um template de ordenamento definido. 
Realmente está ausente o template de ordenamento para sistema numérico ou eu que não achei como fazer? Se não existir eu posso tentar implementar por aqui.

**Comment by leonartex** [comment]
E é impressão minha ou estão sendo impressos nos `\textcite` um espaço a mais entre os nomes e o número da referência? E entre a abertura dos parêntes e primeiro número dentro também?

**Comment by leonartex** [comment]
Já implementei o template para ordenar pela ordem de citação. Eu deixo a definição do `\DeclareSortingTemplate` no `abnt.bbx`, para permitir qualquer um usar se quiser, ou deixo exclusivo para o `abnt-numeric.bbx`?

**Comment by leonartex** [comment]
> E é impressão minha ou estão sendo impressos nos `\textcite` um espaço a mais entre os nomes e o número da referência? E entre a abertura dos parêntes e primeiro número dentro também?

Parece que o espaço do `\textcite` realmente era apenas impressão minha, mas o dos parêntes tá acontecendo e não são em todas as citações:
![image](https://user-images.githubusercontent.com/49103149/213896788-1a0bb028-3f01-428e-8f92-d31fe9d1bbc9.png)
No caso, na linha das citações eu faço um `\textcite` seguido de um `\cite`. Só para deixar claro.

**Comment by leonartex** [comment]
Hehehe descobri só agora que tem o ordenamento `none` que faz o ordenamento por ordem de citação

**Comment by leonartex** [comment]
Identifiquei a causa do bug. Era a opção slashdatarangesep que estava causando. Já corrigi e commitei.

**Comment by dbmrq** [comment]
Isso aqui está resolvido então? Nesse caso, não esquece de fechar. :)
