### ISSUE TITLE
Erro em @inproceedings (Parte de evento em monografa)

### ISSUE THREAD

**Issue by lucasmsoares96** [abntex/abntex2-biblatex#120]
Encontrei isso nas normas do [CEFET-MG](https://www.bu.cefetmg.br/wp-content-uploads-sites-181-2023-04-manual-de-normalizacao-do-cefet-mg-pdf/).
> De acordo com a ABNT NBR 6023 (ABNT, 2018, p. 17), parte de evento em monografia “inclui trabalhos publicados em eventos”. Para trabalhos somente apresentados, recomenda-se como ordem de elementos essenciais: autor, título, subtítulo (se houver) e data de apresentação. Podem-se inserir informações complementares do evento para facilitar a sua identificação. Os elementos essenciais são: autor, título do trabalho, seguidos da expressão In:, nome do evento, numeração do evento (se houver), ano e local (município) de realização, título do documento, local, editora, data de publicação e páginas inicial e final da parte referenciada.
![image](https://github.com/abntex/biblatex-abnt/assets/60808407/e0f3d79a-bc1d-41e9-8408-b0eed1c13de2)
Exemplos:
![image](https://github.com/abntex/biblatex-abnt/assets/60808407/4c533070-91dc-40e0-b575-b4db4ca4da43)

No entanto, o título do documento abaixo não é apresentado em negrito.

```bibtex
@inproceedings{ghemawat2003google,
  title     = {The Google file system},
  author    = {Ghemawat, Sanjay and Gobioff, Howard and Leung, Shun-Tak},
  booktitle = {Proceedings of the nineteenth ACM symposium on Operating systems principles},
  pages     = {29--43},
  year      = {2003}
}
```

![image](https://github.com/abntex/biblatex-abnt/assets/60808407/d47bafd7-ca91-4cb7-8d1d-0982f440e2a4)

**Comment by lucasmsoares96** [comment]
Aparentemente é preciso definir o `eventtitle` manualmente e adaptar o `booktitle`, já que o Google Scholar não fornece.

```bibtex
@inproceedings{ghemawat2003google,
  title     = {The Google file system},
  author    = {Ghemawat, Sanjay and Gobioff, Howard and Leung, Shun-Tak},
  booktitle = {Proceedings of the [...]},
  eventtitle= {nineteenth ACM symposium on Operating systems principles},
  pages     = {29--43},
  year      = {2003}
}
```
![image](https://github.com/abntex/biblatex-abnt/assets/60808407/ed8f2140-bd24-4002-8f88-d27d0cf81504)

**Comment by leonartex** [comment]
Tirando o fato dos colchetes com reticências ter de ser manualmente adicionado, assim, sendo afetado pelo destaque em negrito, acho que não chega necessariamente a ocorrer um problema neste aspecto. Tanto o título do documento quanto o nome do evento são elementos essenciais de acordo com a NBR 6023:2018. 
Algo que penso que pode ficar de lição, e que tenho a intenção de tentar ajudar, talvez seja fazer uma documentação mais detalhada nesses tipos de detalhes menores, que às vezes passam despercebido. Quando eu estava aprendendo sobre LaTeX sofri bastante para achar material que me ajudasse a entender melhor a estrutura do bibtex/biblatex, então acho que pode ser algo bem positivo para a comunidade.

Acho então que esse issue pode ser fechado? Vou ser honesto, estou respondendo isso aqui tarde da noite, cheio de sono, então posso ter deixado algo do issue escapar da vista. Vou fechar o assunto aqui, mas qualquer coisa é só comentar que dá reabrir tranquilamente também, beleza? 
Muito obrigado pela atenção ao projeto! Qualquer outra sugestão ou se identificado algum problema, só falar, porque, agora que estou voltando a contribuir no projeto, a gente tenta ver o que dá pra fazer! Valeuzão!

Ah, e um alerta para ficar atento: é uma boa ficar de olho mesmo nas referências que o Google Acadêmico dá, pois é muito comum, dependendo da estruturação do site e do documento, o Google Acadêmico não conseguir montar a referência certinha. Aí às vezes vem um elemento em um lugar errado ou, então, elementos essenciais ausentes. 
Algo assim é uma tarefa realmente difícil de fazer com precisão de forma automatizada, então, ter uma atenção maior nisso sempre é uma boa.
