### ISSUE TITLE
Ajuda - regras e citações com sobrenomes contendo preposições

### ISSUE THREAD

**Issue by mvlp** [abntex/abntex2-biblatex#127]
Olá, 
Alguém poderia me orientar onde está a regra na ABNT para citar nomes que possuam preposições nos sobrenomes, por exemplo: John Von Neumann, Caterine Le Blank. Além disso, como devo declarar isso no bibtex para que seja citado corretamente usando o biblatex-abnt?
Obrigado

**Comment by dbmrq** [comment]
Boa noite! Você provavelmente vai receber respostas mais rapidamente no grupo latex-br: https://groups.google.com/g/latex-br
