### ISSUE TITLE
Opção comp não funciona

### ISSUE THREAD

**Issue by rodsoasam** [abntex/abntex2-biblatex#85]
Estou usando o `biblatex-abnt` com `style = abnt-numeric` e a opção `comp` não está funcionando. Citação que deveria aparecer 41-43, está como 41,42,43.

Alguém sabe como corrigir isso?

**Comment by leonartex** [comment]
Realmente, procurei aqui no código do `abnt.bbx` e não achei nenhuma citação à opção `comp`. Eu que não olhei direito ou será que removeram sem querer em algum momento, não viram e aí se perdeu entre merges?

Edit.: Hehehe eu que fui burrão e não vi que é definida no `.cbx`, já que apenas afeta a citação haha

**Comment by leonartex** [comment]
Descobri qual é o "problema". Para o modo `comp` a citação de múltiplas obras tem que ser realizado através de um `\cite`, ao invés de um `\cites`.  
Então, ao invés de um: 
`\cites{obra1}{obra2}{obra3}`
Utiliza-se: 
`\cite{obra1,obra2,obra3}`

Acho que é extremamente válido e necessário adicionar essa informação na documentação do pacote. Posso realizar isso depois mais, já que, infelizmente, já bateu o tempo livre que eu tinha pra hoje para mexer com LaTeX.

**Comment by dbmrq** [comment]
Bem observado! Beleza, quando quiser pode fazer a mudança e fechar aqui. Obrigado mais uma vez pelo ótimo trabalho!

**Comment by leonartex** [comment]
Uma última observação: Tanto faz o uso de `\cite` ou `\cites`. O que importa é todas as entradas estarem em um único par de chaves.
