### ISSUE TITLE
É possível usar biblatex-abnt com overleaf?

### ISSUE THREAD

**Issue by Uendert** [abntex/abntex2-biblatex#86]
Olá pessoal,

Gostaria de saber como posso usar biblatex-abnt com o [overleaf](https://www.overleaf.com/).

Obrigado,
Uendert

**Comment by cauachagas** [comment]
Perfeitamente, @Uendert. Se você estiver escrevendo algum documento que use `biblatex`, o `biblatex-abnt` funcionará. Só leve em conta que o `Overleaf` faz atualizações em certos períodos de tempo (A cada ano lança uma versão do `TexLive`, mas não sei afirmar se o `Overleaf` atualiza sempre). O que quero dizer com isso? Talvez os arquivos do `biblatex-abnt` encontrados no `TexLive` do `Overleaf`, não correspondam ao ultimo commit feito aqui neste repositório.


Fiz aqui rápido a versão do modelo canônico do finado `abntex2` com `biblatex-abnt`

https://www.overleaf.com/read/hdhdqyqfvmhb
