### ISSUE TITLE
Indicador de páginas com P maiúsculo na entrada inbook

### ISSUE THREAD

**Issue by andrey-ferreira** [abntex/abntex2-biblatex#88]
Prezado, 
Gostaria de lhe parabenizar pelo brilhante trabalho com o biblatex-abnt.

Ao usar uma entrada com inbook o indicador de páginas fica com "P" maiúsculo.

Segue exemplo de entrada testado junto com a classe abntex2.

```
@inbook{citekey,
  author    = {Teste de tal and Fulano de tal},
  title     = {teste da opção inbook},
  booktitle   = {Título teste},
  publisher = {Eu mesmo},
  year      = {2021},
  pages     = {13-18}
}
```

Saída nas referências

TAL, Teste de; TAL, Fulano de. teste da opção inbook. In: TÍTULO teste. [S.l.]: Eumesmo, 2021. P. 13–18

**Comment by dbmrq** [comment]
Obrigado! Estou sem tempo ultimamente, mas vou deixar aberto aqui e verificar assim que possível.

**Comment by leonartex** [comment]
Descobri como solucionar o bug da inicial maiúscula para página, mas por algum motivo quando eu coloco o código no arquivo bbx não funciona, só no meu .sty que uso no meu documento

O código para resolver é: 
`\xpretofieldformat{pages}{\midsentence}{}{}`

Outra opção também é:
`\xpatchfieldformat{pages}{\mkpageprefix[bookpagination]{#1}}{\midsentence \mkpageprefix[bookpagination]{#1}}{}{}`
Que também não consegui fazer funcionar no .bbx, mas se estiver em um .sty funciona

**Comment by dbmrq** [comment]
Uhm, talvez alguma outra coisa altere as macros depois; vamos ter que investigar

**Comment by dbmrq** [comment]
Ah, agora que eu vi sua PR! Então ela fecha isso aqui, certo?

**Comment by dbmrq** [comment]
Fiz o merge e fechei aqui; se ainda tiver algo de errado fiquem à vontade pra reabrir
